madeyski_epuap.authn:
    path: /epuap/authn
    defaults: { _controller: madeyski_epuap.controller.authn:authnRequestAction }

madeyski_epuap.artifact_resolve:
    path: /epuap/consume
    defaults: { _controller: madeyski_epuap.controller.response_consumer:consumeAction }
    methods: [GET]

