imports:
    - { resource: services/controllers.yml }

services:
    madeyski_epuap.artifact_resolver:
        class: Madeyski\EpuapBundle\Request\ArtifactResolver
        arguments:
            - '@madeyski_epuap.settings.common_signature_provider'

    madeyski_epuap.request.authn_request_generator:
        class: Madeyski\EpuapBundle\Request\AuthnRequestGenerator
        arguments:
            - '@router'
            - '@madeyski_epuap.settings.common_signature_provider'

    madeyski_epuap.settings.common_signature_provider:
        class: Madeyski\EpuapBundle\Settings\CommonSignatureProvider
        arguments:
            - '%epuap_settings%'

    madeyski_epuap.security.response_consumer:
        class: Madeyski\EpuapBundle\Security\Authentication\EpuapResonseConsumer
        arguments:
            - '@madeyski_epuap.artifact_resolver'
            - '@event_dispatcher'

